name: Build on develop

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"
      - name: Enable corepack
        run: corepack enable
      - name: Install dependencies
        run: yarn install
      - name: Debug Workspace
        run: |
          yarn workspaces info
          yarn why @gertalot/sliders
          ls -R
      - name: test
        run: yarn test
      - name: Build
        run: yarn build
