name: Build and Publish Sliders Package

on:
  push:
    branches:
      - main
    paths:
      - "packages/sliders/**"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"
      - name: Enable corepack
        run: corepack enable
      - name: Install dependencies
        run: yarn install
      - name: Debug Workspace
        run: |
          yarn workspaces info
          yarn why @gertalot/sliders
          ls -R
      - name: Build
        run: yarn build
      - name: Publish
        run: yarn npm publish
        working-directory: ./packages/sliders
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
